refactor: modularize schemas
GruppOne/stalker-server pull request #16
Opened 2020-04-15 16:39 UTC by RiccardoAgatea

2020-04-16 15:39 UTC, Alberto1598 commented on api/schemas/Place.yaml
> +        example: Via Trieste
Via Trieste non ha il numero per una dimenticanza

2020-04-17 09:22 UTC, Alberto1598 submitted a review, later dismissed

2020-04-17 09:22 UTC, Alberto1598 commented on api/schemas/Place.yaml
> +        example: Via Trieste
Manca il numero per una dimenticanza

2020-04-17 09:22 UTC, Alberto1598 commented on api/model/LocationInfo.v1.yaml
> +description: "Specifics of an user's current location relative to the places monitored by organizations they're subscribes to."
subscribed (forse?)

2020-04-17 09:22 UTC, Alberto1598 commented on api/model/User.v1.yaml
> +description: Data reprenting an user.
Penso sia un typo e sia representing

2020-04-17 09:22 UTC, Alberto1598 commented on api/model/AppConnection.v1.yaml
> +description: Represents the fact that an user has connected to an organization.
Penso sia "a user"

2020-04-17 09:38 UTC, erclu commented on api/model/LocationInfo.v1.yaml
> +description: "Specifics of an user's current location relative to the places monitored by organizations they're subscribes to."
si dovrebbe essere subscribed. hai risolto tu in locale?

2020-04-17 09:38 UTC, erclu commented on api/model/AppConnection.v1.yaml
> +description: Represents the fact that an user has connected to an organization.
si dovrebbe essere a user

2020-04-17 09:41 UTC, erclu commented
Ho visto che stiamo usando la punteggiatura in modo un po' inconsistente dentro le description e i summary. vogliamo metterci d'accordo? 

tra l'altro volendo si può scrivere una regola custom per il linter dell'api in modo da fare l'enforcing della convenzione scelta:

https://stoplight.io/p/docs/gh/stoplightio/spectral/docs/getting-started/rulesets.md?srn=gh/stoplightio/spectral/docs/getting-started/rulesets.md#adding-a-rule

2020-04-17 09:42 UTC, Alberto1598 commented on api/model/AppConnection.v1.yaml
> +description: Represents the fact that an user has connected to an organization.
Ok fixo allora

2020-04-17 09:47 UTC, erclu requested changes
i file dentro lib/ sono stati committati per sbaglio, vanno eliminati e la cartella aggiunta al gitignore

Ho visto che stiamo usando la punteggiatura in modo un po' inconsistente dentro le description e i summary. vogliamo metterci d'accordo?

tra l'altro volendo si può scrivere una regola custom per il linter dell'api in modo da fare l'enforcing della convenzione scelta:

https://stoplight.io/p/docs/gh/stoplightio/spectral/docs/getting-started/rulesets.md?srn=gh/stoplightio/spectral/docs/getting-started/rulesets.md#adding-a-rule

2020-04-17 09:47 UTC, erclu commented on .idea/.gitignore
> +/workspace.xml
committa pure questo file e togli il gitignore. sarebbe meglio aggiungere cose a quello nella root, piuttosto

2020-04-17 09:47 UTC, erclu commented on api/schemas/security.yaml
> +      refreshUrl: http://localhost:8080/authorize
occhio alla porta specificata qui dentro; non è coerente con quella che usiamo per l'applicazione (11111)

2020-04-17 09:47 UTC, erclu commented on src/main/java/tech/gruppone/stalker/server/repository/Appconfig.java
> +}
questa classe ha un nome sbagliato (dovrebbe essere AppConfig). lo eliminerei perché nell'altra branch c'è già "ApplicationConfiguration"

2020-04-17 09:55 UTC, Alberto1598 commented on src/main/java/tech/gruppone/stalker/server/repository/Appconfig.java
> +}
cazzo mi ero dimenticato di cancellarla

2020-04-17 09:56 UTC, erclu commented on docs/api-todos.md
> +          $ref: "#/components/responses/DefaultResponse"
riuscite anche a documentare l'endpoint /version che restituisce il numero di versione del server? questo dovrebbe andar bene ma dateci una controllatina

2020-04-17 10:01 UTC, Alberto1598 commented on docs/api-todos.md
> +          $ref: "#/components/responses/DefaultResponse"
ok

2020-04-17 17:37 UTC, erclu submitted a review, later dismissed

2020-04-17 17:53 UTC, erclu approved these changes

2020-04-17 17:53 UTC, merged