feat: Implement users endpoint
GruppOne/stalker-server pull request #84
Opened 2020-05-13 13:18 UTC by AlbertoGobbo

2020-05-13 21:24 UTC, Alberto1598 submitted a review, later dismissed

2020-05-14 09:11 UTC, erclu requested changes
solo un paio di cosette e poi penso sia pronta per il merge

per caso riuscite a scrivere i test per userservice? bastano quelli per far passare il gate di sonarcloud

2020-05-14 09:11 UTC, erclu commented on src/main/java/tech/gruppone/stalker/server/model/db/UserDao.java
> +import org.influxdb.annotation.Column;
occhio che questa è l'annotation sbagliata! ci sono due column, uno di influxdb e uno di spring data:
```suggestion
import org.springframework.data.relational.core.mapping.Column;
```

2020-05-14 09:11 UTC, erclu commented on src/main/java/tech/gruppone/stalker/server/model/db/UserDao.java
> +public class UserDao {
qui dovreste specificare il nome della tabella con `@Table("User")`

2020-05-14 09:11 UTC, erclu commented on src/main/java/tech/gruppone/stalker/server/model/db/UserDataDao.java
> +public class UserDataDao {
qui dovreste specificare il nome della tabella con `@Table("UserData")`

2020-05-14 09:11 UTC, erclu commented on src/main/java/tech/gruppone/stalker/server/repositories/UserDataRepository.java
> +  @Query("SELECT * FROM UserData WHERE userId = :id")
se specificate le tabelle come da commenti sopra questa query non serve :)

2020-05-14 09:11 UTC, erclu commented on src/main/java/tech/gruppone/stalker/server/services/UserService.java
> +  public Mono<UserDto> read(final Long userId) {
questo chiamatelo pure con lo stesso nome del repository, cioè `findById`

2020-05-14 09:11 UTC, erclu commented on src/main/java/tech/gruppone/stalker/server/model/api/UserDataDto.java
> +  LocalDateTime creationDateTime;
qua avete omesso il nonnull perché è un parametro non required del json?

2020-05-14 12:41 UTC, AlbertoGobbo commented on src/main/java/tech/gruppone/stalker/server/model/api/UserDataDto.java
> +  LocalDateTime creationDateTime;
Esatto

2020-05-14 12:41 UTC, RiccardoCestaro commented on src/main/java/tech/gruppone/stalker/server/model/api/UserDataDto.java
> +  LocalDateTime creationDateTime;
si

2020-05-14 16:07 UTC, erclu submitted a review, later dismissed

2020-05-14 16:22 UTC, erclu approved these changes

2020-05-14 16:27 UTC, merged