feat: Implements /user/login
GruppOne/stalker-server pull request #86
Opened 2020-05-14 13:31 UTC by AlbertoGobbo

2020-05-15 09:22 UTC, Alberto1598 commented
Per adesso ho messo il secret in application.properties ma va messo assolutamente dentro .env. Il problema è che non legge la stringa in base 64

2020-05-15 09:28 UTC, Alberto1598 commented
Fra l'altro è diminuita la coverage per la classe che ho messo. Quindi o le togliamo dei metodi oppure bisogna testarla tutta

2020-05-15 12:51 UTC, AlbertoGobbo commented
> Fra l'altro è diminuita la coverage per la classe che ho messo. Quindi o le togliamo dei metodi oppure bisogna testarla tutta

Se non è un problema, direi che si può togliere, così almeno il login è pronto all'uso

2020-05-16 09:33 UTC, AlbertoGobbo commented on src/main/java/tech/gruppone/stalker/server/repositories/UserRepository.java
>        "DELETE Users, UserData FROM Users INNER JOIN UserData WHERE Users.id = UserData.userId AND UserData.userId = :id")
Cancellare i metodi:

- public Mono<UserDao> findById(Long id);
-  public Flux<UserDao> findAll();
-  public Mono<Void> deleteUserById(Long id);

Tenere **solo** `public Mono<UserDao> findByEmail(String email);`, in quanto è l'unico metodo utilizzato per /user/login (e quindi anche in questa branch)

L'eliminazione dei suddetti metodi è utile per evitare conflitti una volta che si fa il merge nel master

2020-05-16 09:35 UTC, AlbertoGobbo reviewed
Segnalo solo una piccola cosa nel file **UserRepository.java**.
Per il resto, mi sembra ottimo e chiedo l'approvazione di qualcun altro (tipo @erclu), in quanto non posso approvare o richiedere modifiche. Grazie

2020-05-16 12:26 UTC, erclu requested changes
se volete che il codice venga formattato automaticamente basta che vi apriate un terminale e gli diate il comando: 

```sh
./gradlew spotlessApply --continuous
```

e poi lo lasciate là e ogni volta che salvate un file ve lo formatta.

2020-05-16 12:26 UTC, erclu commented on src/main/java/tech/gruppone/stalker/server/controllers/LoginController.java
> +  public Mono<EncodedJwtDto> logUser(@RequestBody LoginDataDto loginDataDto) {
meglio se nel controller teniamo lo stesso nome dell'endpoint. quindi questo dovrebbe diventare postUserLogin

2020-05-16 12:26 UTC, erclu commented on src/main/java/tech/gruppone/stalker/server/exceptions/LoginFailedException.java
> +public class LoginFailedException extends RuntimeException {
avevo già fatto un'eccezione per questo use case conforme a quanto dichiarato nell'api, è questa:

https://github.com/GruppOne/stalker-server/blob/18a91ce20f06ca31f21ca4106a7a1d05eb98dec6/src/main/java/tech/gruppone/stalker/server/exceptions/UnauthorizedException.java#L6-L12

2020-05-16 12:26 UTC, erclu commented on src/main/java/tech/gruppone/stalker/server/model/api/EncodedJwtDto.java
> +public class EncodedJwtDto {
quiesta classe dovrebbe essere una private static inner class del LoginController (perché è l'unico che la utilizza!)

2020-05-16 12:26 UTC, erclu commented on src/main/java/tech/gruppone/stalker/server/model/api/LoginDataDto.java
> +@AllArgsConstructor
dovremmo cercare di standardizzare queste annotation. hai provato con `@Value`?

2020-05-16 12:26 UTC, erclu commented on src/main/java/tech/gruppone/stalker/server/repositories/UserRepository.java
> +  public Mono<UserDao> findByEmail(String email);
in teoria se dichiari `@Table` e `@Column` sul Dao queste query vengono inferite automaticamente da r2dbc (cioè funziona senza l'annotation)

2020-05-16 12:26 UTC, erclu commented on src/main/java/tech/gruppone/stalker/server/services/LoginService.java
> +  @Autowired private JwtConfiguration jwtConfiguration;
io invece che mettere l'autowired faccio i campi finali e gli do un costruttore con lombok. è più efficiente perché java tratta diversamente i campi `final`!

```suggestion
@AllArgsConstructor
// this makes all fields private and final by default!
@FieldDefaults(level = AccessLevel.PRIVATE, makeFinal = true)
@Service
public class LoginService {

  UserRepository userRepository;
  JwtConfiguration jwtConfiguration;
```

2020-05-16 12:26 UTC, erclu commented on src/main/java/tech/gruppone/stalker/server/services/LoginService.java
> +  @ResponseStatus(code = HttpStatus.CREATED)
come mai c'è il responsestatus su un servizio?

2020-05-16 12:26 UTC, erclu commented on src/main/java/tech/gruppone/stalker/server/services/LoginService.java
> +            Mono.error(new LoginFailedException("Combinazione di username e password errata")));
usare UnauthorizedException

2020-05-16 12:26 UTC, erclu commented on src/main/resources/application.properties
> +# FIXME put encoded secret inside .env
togli pure il fixme!

2020-05-16 12:26 UTC, erclu commented on src/test/java/tech/gruppone/stalker/server/controllers/LoginControllerTest.java
> +        .isCreated();
il top qui sarebbe aggiungere un expect sul valore del token

2020-05-16 12:26 UTC, erclu commented on src/test/java/tech/gruppone/stalker/server/services/LoginServiceTest.java
> +    Assertions.assertThat(encoded).isEqualTo(sut.block());
come alternativa al .block() potete usare una classe chiamata StepVerifier:

```java
StepVerifier
  .create(sut)
  ...
```

è simile a webTestClient concettualmente. ed è più efficiente nel senso che i test finiscono prima!

2020-05-16 16:20 UTC, Alberto1598 commented on src/main/java/tech/gruppone/stalker/server/model/api/EncodedJwtDto.java
> +public class EncodedJwtDto {
Anche il service la utilizza

2020-05-16 16:29 UTC, erclu commented on src/main/java/tech/gruppone/stalker/server/model/api/EncodedJwtDto.java
> +public class EncodedJwtDto {
non dovrebbe. wrappare la richiesta dovrebbe essere responsabilità del controller!

2020-05-21 18:39 UTC, erclu submitted a review, later dismissed

2020-05-21 19:06 UTC, erclu approved these changes

2020-05-21 19:08 UTC, merged